export const habits_data = [
  {
    id: 1,
    name: "Meditate",
    repeat: "Daily",
    goal: "1 time",
    time: "Any Time",
    start_date: "2023-06-18",
    state: "default",
  },
  {
    id: 2,
    name: "Set A To-do list",
    repeat: "Daily",
    goal: "1 time",
    time: "Morning",
    start_date: "2023-01-01",
    state: "default",
  },
  {
    id: 3,
    name: "Read Books",
    repeat: "Weekly",
    goal: "2 times",
    time: "Evening",
    start_date: "2023-06-01",
    state: "deleted",
  },
  {
    id: 4,
    name: "Running",
    repeat: "Daily",
    goal: "2 times",
    time: "Any Time",
    start_date: "2023-03-01",
    state: "archived",
  },
];
